obj-y := z48soc_setup.o z48soc_mem.o z48soc_time.o z48soc_int.o z48soc_cmdline.o

obj-$(CONFIG_SMP) += z48soc_smp.o
obj-$(CONFIG_MACH_Z48SOC_DE2_70) += z48soc_mach_de2_70.o
obj-$(CONFIG_MACH_Z48SOC_DE2_115) += z48soc_mach_de2_115.o
